-- ELECTRO PWA Database Schema
-- PostgreSQL migration file

-- Users table
CREATE TABLE IF NOT EXISTS users (
    id SERIAL PRIMARY KEY,
    login VARCHAR(50) UNIQUE NOT NULL,
    password_hash VARCHAR(255) NOT NULL,
    role VARCHAR(20) NOT NULL DEFAULT 'commander' CHECK (role IN ('admin', 'electrician', 'commander')),
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

-- Objects (enterprises, facilities)
CREATE TABLE IF NOT EXISTS objects (
    id SERIAL PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    code VARCHAR(50),
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

-- Premises (wagons, rooms, buildings)
CREATE TABLE IF NOT EXISTS premises (
    id SERIAL PRIMARY KEY,
    object_id INTEGER REFERENCES objects(id) ON DELETE CASCADE,
    name VARCHAR(100) NOT NULL,
    number VARCHAR(20),
    type VARCHAR(20) DEFAULT 'wagon' CHECK (type IN ('wagon', 'room', 'building')),
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

-- Heaters
CREATE TABLE IF NOT EXISTS heaters (
    id SERIAL PRIMARY KEY,
    premise_id INTEGER REFERENCES premises(id) ON DELETE SET NULL,
    serial VARCHAR(100),
    name VARCHAR(100) NOT NULL,
    power_kw DECIMAL(8,2),
    elements INTEGER,
    manufacture_date DATE,
    photo_url VARCHAR(255),
    status VARCHAR(20) NOT NULL DEFAULT 'active' CHECK (status IN ('active', 'repair', 'warehouse', 'moved')),
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

-- Stickers (labels applied to heaters)
CREATE TABLE IF NOT EXISTS stickers (
    id SERIAL PRIMARY KEY,
    heater_id INTEGER REFERENCES heaters(id) ON DELETE CASCADE,
    number VARCHAR(10) NOT NULL,
    check_date DATE,
    electrician_id INTEGER REFERENCES users(id),
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

-- Heater events (history log)
CREATE TABLE IF NOT EXISTS heater_events (
    id SERIAL PRIMARY KEY,
    heater_id INTEGER REFERENCES heaters(id) ON DELETE CASCADE,
    user_id INTEGER REFERENCES users(id),
    event_type VARCHAR(30) NOT NULL CHECK (event_type IN ('status_change', 'premise_change', 'sticker_applied', 'photo_updated')),
    from_premise_id INTEGER REFERENCES premises(id),
    to_premise_id INTEGER REFERENCES premises(id),
    old_status VARCHAR(20),
    new_status VARCHAR(20),
    comment TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

-- Sync log (for offline operations)
CREATE TABLE IF NOT EXISTS sync_log (
    id SERIAL PRIMARY KEY,
    user_id INTEGER REFERENCES users(id),
    action VARCHAR(100) NOT NULL,
    payload JSONB,
    synced BOOLEAN DEFAULT FALSE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

-- Indexes for performance
CREATE INDEX IF NOT EXISTS idx_heaters_premise ON heaters(premise_id);
CREATE INDEX IF NOT EXISTS idx_heaters_status ON heaters(status);
CREATE INDEX IF NOT EXISTS idx_premises_object ON premises(object_id);
CREATE INDEX IF NOT EXISTS idx_stickers_heater ON stickers(heater_id);
CREATE INDEX IF NOT EXISTS idx_events_heater ON heater_events(heater_id);
CREATE INDEX IF NOT EXISTS idx_events_created ON heater_events(created_at DESC);
CREATE INDEX IF NOT EXISTS idx_sync_log_synced ON sync_log(synced) WHERE synced = FALSE;

-- Create default admin user (password: admin123)
-- The password hash is generated by the application on first run
-- This is handled by auth.js ensureAdminUser() function
